"""
@generated by codestare-proto-plus.  Do not edit manually!
"""
import proto
from proto import (
    Field,
    INT32,
    RepeatedField,
    STRING,
)

from proto.message import (
    Message,
)

from ubii.proto.v1.types.topicData.topicDataRecord_pb_plus import (
    TopicDataRecord,
)


__protobuf__ = proto.module(
    package="ubii.proto.v1",
    manifest={
        "LockstepProcessingRequest",
        "LockstepProcessingReply",
    }
)


class LockstepProcessingRequest(Message):
    """Generated from ubii/proto/v1/types/processing/lockstepProcessing.proto

    Attributes:
        processing_module_ids (:obj:`RepeatedField`): :obj:`RepeatedField` of type :obj:`STRING`
        records (:obj:`RepeatedField`): :obj:`RepeatedField` of type :obj:`TopicDataRecord`
        delta_time_ms (:obj:`Field`): :obj:`Field` of type :obj:`INT32`

    """
    processing_module_ids = RepeatedField(
        STRING,
        number=1,
    )
    records = RepeatedField(
        TopicDataRecord,
        number=2,
    )
    delta_time_ms = Field(
        INT32,
        number=3,
    )


class LockstepProcessingReply(Message):
    """Generated from ubii/proto/v1/types/processing/lockstepProcessing.proto

    Attributes:
        processing_module_ids (:obj:`RepeatedField`): :obj:`RepeatedField` of type :obj:`STRING`
        records (:obj:`RepeatedField`): :obj:`RepeatedField` of type :obj:`TopicDataRecord`

    """
    processing_module_ids = RepeatedField(
        STRING,
        number=1,
    )
    records = RepeatedField(
        TopicDataRecord,
        number=2,
    )

