"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing
import typing_extensions
import ubii.proto.clients.client_pb2
import ubii.proto.dataStructure.lists_pb2
import ubii.proto.devices.device_pb2
import ubii.proto.devices.topicDemux_pb2
import ubii.proto.devices.topicMux_pb2
import ubii.proto.general.error_pb2
import ubii.proto.general.success_pb2
import ubii.proto.processing.lockstepProcessing_pb2
import ubii.proto.processing.processingModule_pb2
import ubii.proto.servers.server_pb2
import ubii.proto.services.service_pb2
import ubii.proto.sessions.session_pb2

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class ServiceReply(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    SUCCESS_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    CLIENT_FIELD_NUMBER: builtins.int
    DEVICE_FIELD_NUMBER: builtins.int
    SERVER_FIELD_NUMBER: builtins.int
    SESSION_FIELD_NUMBER: builtins.int
    SESSION_LIST_FIELD_NUMBER: builtins.int
    PROCESSING_MODULE_FIELD_NUMBER: builtins.int
    PROCESSING_MODULE_LIST_FIELD_NUMBER: builtins.int
    STRING_LIST_FIELD_NUMBER: builtins.int
    TOPIC_MUX_FIELD_NUMBER: builtins.int
    TOPIC_MUX_LIST_FIELD_NUMBER: builtins.int
    TOPIC_DEMUX_FIELD_NUMBER: builtins.int
    TOPIC_DEMUX_LIST_FIELD_NUMBER: builtins.int
    CLIENT_LIST_FIELD_NUMBER: builtins.int
    DEVICE_LIST_FIELD_NUMBER: builtins.int
    SERVICE_FIELD_NUMBER: builtins.int
    SERVICE_LIST_FIELD_NUMBER: builtins.int
    LOCKSTEP_PROCESSING_REPLY_FIELD_NUMBER: builtins.int
    @property
    def success(self) -> ubii.proto.general.success_pb2.Success: ...
    @property
    def error(self) -> ubii.proto.general.error_pb2.Error: ...
    @property
    def client(self) -> ubii.proto.clients.client_pb2.Client: ...
    @property
    def device(self) -> ubii.proto.devices.device_pb2.Device: ...
    @property
    def server(self) -> ubii.proto.servers.server_pb2.Server: ...
    @property
    def session(self) -> ubii.proto.sessions.session_pb2.Session: ...
    @property
    def session_list(self) -> ubii.proto.sessions.session_pb2.SessionList: ...
    @property
    def processing_module(self) -> ubii.proto.processing.processingModule_pb2.ProcessingModule: ...
    @property
    def processing_module_list(self) -> ubii.proto.processing.processingModule_pb2.ProcessingModuleList: ...
    @property
    def string_list(self) -> ubii.proto.dataStructure.lists_pb2.StringList: ...
    @property
    def topic_mux(self) -> ubii.proto.devices.topicMux_pb2.TopicMux: ...
    @property
    def topic_mux_list(self) -> ubii.proto.devices.topicMux_pb2.TopicMuxList: ...
    @property
    def topic_demux(self) -> ubii.proto.devices.topicDemux_pb2.TopicDemux: ...
    @property
    def topic_demux_list(self) -> ubii.proto.devices.topicDemux_pb2.TopicDemuxList: ...
    @property
    def client_list(self) -> ubii.proto.clients.client_pb2.ClientList: ...
    @property
    def device_list(self) -> ubii.proto.devices.device_pb2.DeviceList: ...
    @property
    def service(self) -> ubii.proto.services.service_pb2.Service: ...
    @property
    def service_list(self) -> ubii.proto.services.service_pb2.ServiceList: ...
    @property
    def lockstep_processing_reply(self) -> ubii.proto.processing.lockstepProcessing_pb2.LockstepProcessingReply: ...
    def __init__(self,
        *,
        success : typing.Optional[ubii.proto.general.success_pb2.Success] = ...,
        error : typing.Optional[ubii.proto.general.error_pb2.Error] = ...,
        client : typing.Optional[ubii.proto.clients.client_pb2.Client] = ...,
        device : typing.Optional[ubii.proto.devices.device_pb2.Device] = ...,
        server : typing.Optional[ubii.proto.servers.server_pb2.Server] = ...,
        session : typing.Optional[ubii.proto.sessions.session_pb2.Session] = ...,
        session_list : typing.Optional[ubii.proto.sessions.session_pb2.SessionList] = ...,
        processing_module : typing.Optional[ubii.proto.processing.processingModule_pb2.ProcessingModule] = ...,
        processing_module_list : typing.Optional[ubii.proto.processing.processingModule_pb2.ProcessingModuleList] = ...,
        string_list : typing.Optional[ubii.proto.dataStructure.lists_pb2.StringList] = ...,
        topic_mux : typing.Optional[ubii.proto.devices.topicMux_pb2.TopicMux] = ...,
        topic_mux_list : typing.Optional[ubii.proto.devices.topicMux_pb2.TopicMuxList] = ...,
        topic_demux : typing.Optional[ubii.proto.devices.topicDemux_pb2.TopicDemux] = ...,
        topic_demux_list : typing.Optional[ubii.proto.devices.topicDemux_pb2.TopicDemuxList] = ...,
        client_list : typing.Optional[ubii.proto.clients.client_pb2.ClientList] = ...,
        device_list : typing.Optional[ubii.proto.devices.device_pb2.DeviceList] = ...,
        service : typing.Optional[ubii.proto.services.service_pb2.Service] = ...,
        service_list : typing.Optional[ubii.proto.services.service_pb2.ServiceList] = ...,
        lockstep_processing_reply : typing.Optional[ubii.proto.processing.lockstepProcessing_pb2.LockstepProcessingReply] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["client",b"client","client_list",b"client_list","device",b"device","device_list",b"device_list","error",b"error","lockstep_processing_reply",b"lockstep_processing_reply","processing_module",b"processing_module","processing_module_list",b"processing_module_list","server",b"server","service",b"service","service_list",b"service_list","session",b"session","session_list",b"session_list","string_list",b"string_list","success",b"success","topic_demux",b"topic_demux","topic_demux_list",b"topic_demux_list","topic_mux",b"topic_mux","topic_mux_list",b"topic_mux_list","type",b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["client",b"client","client_list",b"client_list","device",b"device","device_list",b"device_list","error",b"error","lockstep_processing_reply",b"lockstep_processing_reply","processing_module",b"processing_module","processing_module_list",b"processing_module_list","server",b"server","service",b"service","service_list",b"service_list","session",b"session","session_list",b"session_list","string_list",b"string_list","success",b"success","topic_demux",b"topic_demux","topic_demux_list",b"topic_demux_list","topic_mux",b"topic_mux","topic_mux_list",b"topic_mux_list","type",b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["type",b"type"]) -> typing.Optional[typing_extensions.Literal["success","error","client","device","server","session","session_list","processing_module","processing_module_list","string_list","topic_mux","topic_mux_list","topic_demux","topic_demux_list","client_list","device_list","service","service_list","lockstep_processing_reply"]]: ...
global___ServiceReply = ServiceReply
