"""
@generated by codestare-proto-plus.  Do not edit manually!
"""
from builtins import (
    str,
)

from proto import (
    ENUM,
    Field,
    STRING,
    module,
)

from proto.message import (
    Message,
)

from ubii.proto.v1.dataStructure.buttonEventType_pb_plus import (
    ButtonEventType,
)


__protobuf__ = module(
    package="ubii.proto.v1.dataStructure",
    marshal="ubii.proto.v1",
    manifest={
        "KeyEvent",
    }
)


class KeyEvent(Message):
    """
    Attributes:
        type (proto.fields.Field): :obj:`~proto.fields.Field` of type
            :obj:`~ubii.proto.v1.dataStructure.buttonEventType_pb_plus.ButtonEventType`
        key (proto.fields.Field): :obj:`~proto.fields.Field` of type
            :obj:`~proto.primitives.ProtoType.STRING`
    """

    type: ButtonEventType = Field(
        ENUM,
        number=1,
        enum=ButtonEventType,
    )
    key: str = Field(
        STRING,
        number=2,
    )

