"""
@generated by codestare-proto-plus.  Do not edit manually!
"""
from builtins import (
    bool,
    float,
    int,
    str,
)

from proto import (
    BOOL,
    DOUBLE,
    FLOAT,
    INT32,
    RepeatedField,
    STRING,
    module,
)

from proto.message import (
    Message,
)

from typing import (
    Sequence,
)


__protobuf__ = module(
    package="ubii.proto.v1.dataStructure",
    marshal="ubii.proto.v1",
    manifest={
        "StringList",
        "DoubleList",
        "FloatList",
        "BoolList",
        "Int32List",
    }
)


class StringList(Message):
    """
    Attributes:
        elements (proto.fields.RepeatedField): :obj:`~proto.fields.RepeatedField` of type
            :obj:`~proto.primitives.ProtoType.STRING`
    """

    elements: Sequence[str] = RepeatedField(
        STRING,
        number=1,
    )


class DoubleList(Message):
    """
    Attributes:
        elements (proto.fields.RepeatedField): :obj:`~proto.fields.RepeatedField` of type
            :obj:`~proto.primitives.ProtoType.DOUBLE`
    """

    elements: Sequence[float] = RepeatedField(
        DOUBLE,
        number=1,
    )


class FloatList(Message):
    """
    Attributes:
        elements (proto.fields.RepeatedField): :obj:`~proto.fields.RepeatedField` of type
            :obj:`~proto.primitives.ProtoType.FLOAT`
    """

    elements: Sequence[float] = RepeatedField(
        FLOAT,
        number=1,
    )


class BoolList(Message):
    """
    Attributes:
        elements (proto.fields.RepeatedField): :obj:`~proto.fields.RepeatedField` of type
            :obj:`~proto.primitives.ProtoType.BOOL`
    """

    elements: Sequence[bool] = RepeatedField(
        BOOL,
        number=1,
    )


class Int32List(Message):
    """
    Attributes:
        elements (proto.fields.RepeatedField): :obj:`~proto.fields.RepeatedField` of type
            :obj:`~proto.primitives.ProtoType.INT32`
    """

    elements: Sequence[int] = RepeatedField(
        INT32,
        number=1,
    )

