"""
@generated by codestare-proto-plus.  Do not edit manually!
"""
from proto import (
    DOUBLE,
    Field,
    module,
)

from proto.message import (
    Message,
)


__protobuf__ = module(
    package="ubii.proto.v1",
    manifest={
        "Matrix4x4",
    }
)


class Matrix4x4(Message):
    """Generated from ubii/proto/v1/dataStructure/matrix4x4.proto

    Attributes:
        m00 (proto.fields.Field): :obj:`~proto.fields.Field` of type
             :obj:`~proto.DOUBLE`
        m01 (proto.fields.Field): :obj:`~proto.fields.Field` of type
             :obj:`~proto.DOUBLE`
        m02 (proto.fields.Field): :obj:`~proto.fields.Field` of type
             :obj:`~proto.DOUBLE`
        m03 (proto.fields.Field): :obj:`~proto.fields.Field` of type
             :obj:`~proto.DOUBLE`
        m10 (proto.fields.Field): :obj:`~proto.fields.Field` of type
             :obj:`~proto.DOUBLE`
        m11 (proto.fields.Field): :obj:`~proto.fields.Field` of type
             :obj:`~proto.DOUBLE`
        m12 (proto.fields.Field): :obj:`~proto.fields.Field` of type
             :obj:`~proto.DOUBLE`
        m13 (proto.fields.Field): :obj:`~proto.fields.Field` of type
             :obj:`~proto.DOUBLE`
        m20 (proto.fields.Field): :obj:`~proto.fields.Field` of type
             :obj:`~proto.DOUBLE`
        m21 (proto.fields.Field): :obj:`~proto.fields.Field` of type
             :obj:`~proto.DOUBLE`
        m22 (proto.fields.Field): :obj:`~proto.fields.Field` of type
             :obj:`~proto.DOUBLE`
        m23 (proto.fields.Field): :obj:`~proto.fields.Field` of type
             :obj:`~proto.DOUBLE`
        m30 (proto.fields.Field): :obj:`~proto.fields.Field` of type
             :obj:`~proto.DOUBLE`
        m31 (proto.fields.Field): :obj:`~proto.fields.Field` of type
             :obj:`~proto.DOUBLE`
        m32 (proto.fields.Field): :obj:`~proto.fields.Field` of type
             :obj:`~proto.DOUBLE`
        m33 (proto.fields.Field): :obj:`~proto.fields.Field` of type
             :obj:`~proto.DOUBLE`

    """
    m00 = Field(
        DOUBLE,
        number=1,
    )
    m01 = Field(
        DOUBLE,
        number=2,
    )
    m02 = Field(
        DOUBLE,
        number=3,
    )
    m03 = Field(
        DOUBLE,
        number=4,
    )
    m10 = Field(
        DOUBLE,
        number=5,
    )
    m11 = Field(
        DOUBLE,
        number=6,
    )
    m12 = Field(
        DOUBLE,
        number=7,
    )
    m13 = Field(
        DOUBLE,
        number=8,
    )
    m20 = Field(
        DOUBLE,
        number=9,
    )
    m21 = Field(
        DOUBLE,
        number=10,
    )
    m22 = Field(
        DOUBLE,
        number=11,
    )
    m23 = Field(
        DOUBLE,
        number=12,
    )
    m30 = Field(
        DOUBLE,
        number=13,
    )
    m31 = Field(
        DOUBLE,
        number=14,
    )
    m32 = Field(
        DOUBLE,
        number=15,
    )
    m33 = Field(
        DOUBLE,
        number=16,
    )

