"""
@generated by codestare-proto-plus.  Do not edit manually!
"""
from builtins import (
    float,
)

from proto import (
    DOUBLE,
    Field,
    MESSAGE,
    RepeatedField,
    module,
)

from proto.message import (
    Message,
)

from typing import (
    Sequence,
)


__protobuf__ = module(
    package="ubii.proto.v1.dataStructure",
    marshal="ubii.proto.v1",
    manifest={
        "Vector2",
        "Vector2List",
    }
)


class Vector2(Message):
    """
    Attributes:
        x (proto.fields.Field): :obj:`~proto.fields.Field` of type
            :obj:`~proto.primitives.ProtoType.DOUBLE`
        y (proto.fields.Field): :obj:`~proto.fields.Field` of type
            :obj:`~proto.primitives.ProtoType.DOUBLE`
    """

    x: float = Field(
        DOUBLE,
        number=1,
    )
    y: float = Field(
        DOUBLE,
        number=2,
    )


class Vector2List(Message):
    """
    Attributes:
        elements (proto.fields.RepeatedField): :obj:`~proto.fields.RepeatedField` of type
            :obj:`~.Vector2`
    """

    elements: Sequence[Vector2] = RepeatedField(
        MESSAGE,
        number=1,
        message=Vector2,
    )

