"""
@generated by codestare-proto-plus.  Do not edit manually!
"""
from proto import (
    DOUBLE,
    Field,
    RepeatedField,
    module,
)

from proto.message import (
    Message,
)


__protobuf__ = module(
    package="ubii.proto.v1",
    manifest={
        "Vector3",
        "Vector3List",
    }
)


class Vector3(Message):
    """Generated from ubii/proto/v1/dataStructure/vector3.proto

    Attributes:
        x (proto.fields.Field): :obj:`~proto.fields.Field` of type
             :obj:`~proto.DOUBLE`
        y (proto.fields.Field): :obj:`~proto.fields.Field` of type
             :obj:`~proto.DOUBLE`
        z (proto.fields.Field): :obj:`~proto.fields.Field` of type
             :obj:`~proto.DOUBLE`

    """
    x = Field(
        DOUBLE,
        number=1,
    )
    y = Field(
        DOUBLE,
        number=2,
    )
    z = Field(
        DOUBLE,
        number=3,
    )


class Vector3List(Message):
    """Generated from ubii/proto/v1/dataStructure/vector3.proto

    Attributes:
        elements (proto.fields.RepeatedField): :obj:`~proto.fields.RepeatedField` of
             type :obj:`~.Vector3`

    """
    elements = RepeatedField(
        Vector3,
        number=1,
    )

