"""
@generated by codestare-proto-plus.  Do not edit manually!
isort:skip_file
"""
import proto
from proto import (
    Field,
    STRING,
)

from proto.message import (
    Message,
)

from ubii.proto_v1.types.dataStructure.buttonEventType_pb_plus import (
    ButtonEventType,
)


__protobuf__ = proto.module(
    package="ubii.interact.v1",
    manifest={
        "KeyEvent",
    }
)


class KeyEvent(Message):
    type = Field(
        ButtonEventType,
        number=1,
    )
    key = Field(
        STRING,
        number=2,
    )


