"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import proto
import proto.message
import ubii.proto.devices.topicDemux_pb_plus
import ubii.proto.devices.topicMux_pb_plus

class TopicInputMapping(proto.message.Message):
    input_name = proto.Field(proto.STRING, number=0)
    topic = proto.Field(proto.STRING, number=1)
    topic_mux = proto.Field(ubii.proto.devices.topicMux_pb_plus.TopicMux, number=2)

class TopicInputMappingList(proto.message.Message):
    elements = proto.RepeatedField(TopicInputMapping, number=0)

class TopicOutputMapping(proto.message.Message):
    output_name = proto.Field(proto.STRING, number=0)
    topic = proto.Field(proto.STRING, number=1)
    topic_demux = proto.Field(ubii.proto.devices.topicDemux_pb_plus.TopicDemux, number=2)

class TopicOutputMappingList(proto.message.Message):
    elements = proto.RepeatedField(TopicOutputMapping, number=0)

class IOMapping(proto.message.Message):
    processing_module_id = proto.Field(proto.STRING, number=0)
    input_mappings = proto.RepeatedField(TopicInputMapping, number=1)
    output_mappings = proto.RepeatedField(TopicOutputMapping, number=2)
    processing_module_name = proto.Field(proto.STRING, number=3)

class IOMappingList(proto.message.Message):
    elements = proto.RepeatedField(IOMapping, number=0)
