"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import proto
import proto.message
import ubii.proto.processing.processingModule_pb_plus
import ubii.proto.sessions.ioMappings_pb_plus

class SessionStatus(proto.Enum):
    CREATED = 0
    RUNNING = 1
    PAUSED = 2
    STOPPED = 3

class Session(proto.message.Message):
    id = proto.Field(proto.STRING, number=0)
    name = proto.Field(proto.STRING, number=1)
    processing_modules = proto.RepeatedField(ubii.proto.processing.processingModule_pb_plus.ProcessingModule, number=2)
    io_mappings = proto.RepeatedField(ubii.proto.sessions.ioMappings_pb_plus.IOMapping, number=3)
    tags = proto.RepeatedField(proto.STRING, number=4)
    description = proto.Field(proto.STRING, number=5)
    authors = proto.RepeatedField(proto.STRING, number=6)
    status = proto.Field(SessionStatus, number=7)
    editable = proto.Field(proto.BOOL, number=8)

class SessionList(proto.message.Message):
    elements = proto.RepeatedField(Session, number=0)
