"""
@generated by codestare-proto-plus.  Do not edit manually!

Note:
    __init__.py files for packages are autogenerated, and import all messages from submodules to keep import names consistent with the directory structure of the ``.proto`` source files.
"""
from ubii.proto.v1.types.services.serviceReply_pb_plus import (
    ServiceReply,
)

from ubii.proto.v1.types.services.serviceRequest_pb_plus import (
    ServiceRequest,
)

from ubii.proto.v1.types.services.service_pb_plus import (
    Service,
    ServiceList,
)


__all__ = (
    "Service",
    "ServiceList",
    "ServiceReply",
    "ServiceRequest",
)