"""
@generated by codestare-proto-plus.  Do not edit manually!
"""
import proto
from proto import (
    Enum,
    Field,
    RepeatedField,
    STRING,
)

from proto.message import (
    Message,
)


__protobuf__ = proto.module(
    package="ubii.proto.v1",
    manifest={
        "Component",
        "ComponentList",
    }
)


class Component(Message):
    """Generated from ubii/proto/v1/types/devices/component.proto

    Attributes:
        topic (:obj:`Field`): :obj:`Field` of type :obj:`STRING`
        message_format (:obj:`Field`): :obj:`Field` of type :obj:`STRING`
        io_type (:obj:`Field`): :obj:`Field` of type :obj:`IOType`
        device_id (:obj:`Field`): :obj:`Field` of type :obj:`STRING`
        tags (:obj:`RepeatedField`): :obj:`RepeatedField` of type :obj:`STRING`
        description (:obj:`Field`): :obj:`Field` of type :obj:`STRING`
        id (:obj:`Field`): :obj:`Field` of type :obj:`STRING`
        name (:obj:`Field`): :obj:`Field` of type :obj:`STRING`

    """
    class IOType(Enum):
        PUBLISHER = 0
        SUBSCRIBER = 1

    topic = Field(
        STRING,
        number=1,
    )
    message_format = Field(
        STRING,
        number=2,
    )
    io_type = Field(
        IOType,
        number=3,
    )
    device_id = Field(
        STRING,
        number=4,
    )
    tags = RepeatedField(
        STRING,
        number=5,
    )
    description = Field(
        STRING,
        number=6,
    )
    id = Field(
        STRING,
        number=7,
    )
    name = Field(
        STRING,
        number=8,
    )


class ComponentList(Message):
    """Generated from ubii/proto/v1/types/devices/component.proto

    Attributes:
        elements (:obj:`RepeatedField`): :obj:`RepeatedField` of type :obj:`Component`

    """
    elements = RepeatedField(
        Component,
        number=1,
    )

