"""
@generated by codestare-proto-plus.  Do not edit manually!
"""
import proto
from proto import (
    Field,
    RepeatedField,
    STRING,
)

from proto.message import (
    Message,
)


__protobuf__ = proto.module(
    package="ubii.proto.v1",
    manifest={
        "TopicDemux",
        "TopicDemuxList",
    }
)


class TopicDemux(Message):
    """Generated from ubii/proto/v1/types/devices/topicDemux.proto

    Attributes:
        id (:obj:`Field`): :obj:`Field` of type :obj:`STRING`
        name (:obj:`Field`): :obj:`Field` of type :obj:`STRING`
        data_type (:obj:`Field`): :obj:`Field` of type :obj:`STRING`
        output_topic_format (:obj:`Field`): :obj:`Field` of type :obj:`STRING`

    """
    id = Field(
        STRING,
        number=1,
    )
    name = Field(
        STRING,
        number=2,
    )
    data_type = Field(
        STRING,
        number=3,
    )
    output_topic_format = Field(
        STRING,
        number=4,
    )


class TopicDemuxList(Message):
    """Generated from ubii/proto/v1/types/devices/topicDemux.proto

    Attributes:
        elements (:obj:`RepeatedField`): :obj:`RepeatedField` of type :obj:`TopicDemux`

    """
    elements = RepeatedField(
        TopicDemux,
        number=1,
    )

