"""
@generated by codestare-proto-plus.  Do not edit manually!
"""
import proto
from proto import (
    Field,
    RepeatedField,
    STRING,
)

from proto.message import (
    Message,
)


__protobuf__ = proto.module(
    package="ubii.proto.v1",
    manifest={
        "TopicMux",
        "TopicMuxList",
    }
)


class TopicMux(Message):
    """Generated from ubii/proto/v1/types/devices/topicMux.proto

    Attributes:
        id (:obj:`Field`): :obj:`Field` of type :obj:`STRING`
        name (:obj:`Field`): :obj:`Field` of type :obj:`STRING`
        data_type (:obj:`Field`): :obj:`Field` of type :obj:`STRING`
        topic_selector (:obj:`Field`): :obj:`Field` of type :obj:`STRING`
        identity_match_pattern (:obj:`Field`): :obj:`Field` of type :obj:`STRING`

    """
    id = Field(
        STRING,
        number=1,
    )
    name = Field(
        STRING,
        number=2,
    )
    data_type = Field(
        STRING,
        number=3,
    )
    topic_selector = Field(
        STRING,
        number=4,
    )
    identity_match_pattern = Field(
        STRING,
        number=5,
    )


class TopicMuxList(Message):
    """Generated from ubii/proto/v1/types/devices/topicMux.proto

    Attributes:
        elements (:obj:`RepeatedField`): :obj:`RepeatedField` of type :obj:`TopicMux`

    """
    elements = RepeatedField(
        TopicMux,
        number=1,
    )

