# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ubii/proto_baseline/devices/topicDemux.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,ubii/proto_baseline/devices/topicDemux.proto\x12\x1bubii.proto_baseline.devices\"V\n\nTopicDemux\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\tdata_type\x18\x03 \x01(\t\x12\x1b\n\x13output_topic_format\x18\x04 \x01(\t\"K\n\x0eTopicDemuxList\x12\x39\n\x08\x65lements\x18\x01 \x03(\x0b\x32\'.ubii.proto_baseline.devices.TopicDemuxb\x06proto3')



_TOPICDEMUX = DESCRIPTOR.message_types_by_name['TopicDemux']
_TOPICDEMUXLIST = DESCRIPTOR.message_types_by_name['TopicDemuxList']
TopicDemux = _reflection.GeneratedProtocolMessageType('TopicDemux', (_message.Message,), {
  'DESCRIPTOR' : _TOPICDEMUX,
  '__module__' : 'ubii.proto_baseline.devices.topicDemux_pb2'
  # @@protoc_insertion_point(class_scope:ubii.proto_baseline.devices.TopicDemux)
  })
_sym_db.RegisterMessage(TopicDemux)

TopicDemuxList = _reflection.GeneratedProtocolMessageType('TopicDemuxList', (_message.Message,), {
  'DESCRIPTOR' : _TOPICDEMUXLIST,
  '__module__' : 'ubii.proto_baseline.devices.topicDemux_pb2'
  # @@protoc_insertion_point(class_scope:ubii.proto_baseline.devices.TopicDemuxList)
  })
_sym_db.RegisterMessage(TopicDemuxList)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TOPICDEMUX._serialized_start=77
  _TOPICDEMUX._serialized_end=163
  _TOPICDEMUXLIST._serialized_start=165
  _TOPICDEMUXLIST._serialized_end=240
# @@protoc_insertion_point(module_scope)
