# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ubii/proto_baseline/devices/topicMux.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*ubii/proto_baseline/devices/topicMux.proto\x12\x1bubii.proto_baseline.devices\"o\n\x08TopicMux\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\tdata_type\x18\x03 \x01(\t\x12\x16\n\x0etopic_selector\x18\x04 \x01(\t\x12\x1e\n\x16identity_match_pattern\x18\x05 \x01(\t\"G\n\x0cTopicMuxList\x12\x37\n\x08\x65lements\x18\x01 \x03(\x0b\x32%.ubii.proto_baseline.devices.TopicMuxb\x06proto3')



_TOPICMUX = DESCRIPTOR.message_types_by_name['TopicMux']
_TOPICMUXLIST = DESCRIPTOR.message_types_by_name['TopicMuxList']
TopicMux = _reflection.GeneratedProtocolMessageType('TopicMux', (_message.Message,), {
  'DESCRIPTOR' : _TOPICMUX,
  '__module__' : 'ubii.proto_baseline.devices.topicMux_pb2'
  # @@protoc_insertion_point(class_scope:ubii.proto_baseline.devices.TopicMux)
  })
_sym_db.RegisterMessage(TopicMux)

TopicMuxList = _reflection.GeneratedProtocolMessageType('TopicMuxList', (_message.Message,), {
  'DESCRIPTOR' : _TOPICMUXLIST,
  '__module__' : 'ubii.proto_baseline.devices.topicMux_pb2'
  # @@protoc_insertion_point(class_scope:ubii.proto_baseline.devices.TopicMuxList)
  })
_sym_db.RegisterMessage(TopicMuxList)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TOPICMUX._serialized_start=75
  _TOPICMUX._serialized_end=186
  _TOPICMUXLIST._serialized_start=188
  _TOPICMUXLIST._serialized_end=259
# @@protoc_insertion_point(module_scope)
