"""
@generated by codestare-proto-plus.  Do not edit manually!
"""
import proto
from proto import (
    Field,
    RepeatedField,
    STRING,
)

from proto.message import (
    Message,
)


__protobuf__ = proto.module(
    package="ubii.proto.v1",
    manifest={
        "Success",
        "SuccessList",
    }
)


class Success(Message):
    """Generated from ubii/proto/v1/types/general/success.proto

    Attributes:
        title (:obj:`Field`): :obj:`Field` of type :obj:`STRING`
        message (:obj:`Field`): :obj:`Field` of type :obj:`STRING`

    """
    title = Field(
        STRING,
        number=1,
    )
    message = Field(
        STRING,
        number=2,
    )


class SuccessList(Message):
    """Generated from ubii/proto/v1/types/general/success.proto

    Attributes:
        elements (:obj:`RepeatedField`): :obj:`RepeatedField` of type :obj:`Success`

    """
    elements = RepeatedField(
        Success,
        number=1,
    )

