"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class Component(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class IOType(_IOType, metaclass=_IOTypeEnumTypeWrapper):
        pass
    class _IOType:
        V = typing.NewType('V', builtins.int)
    class _IOTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_IOType.V], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        PUBLISHER = Component.IOType.V(0)
        SUBSCRIBER = Component.IOType.V(1)

    PUBLISHER = Component.IOType.V(0)
    SUBSCRIBER = Component.IOType.V(1)

    TOPIC_FIELD_NUMBER: builtins.int
    MESSAGE_FORMAT_FIELD_NUMBER: builtins.int
    IO_TYPE_FIELD_NUMBER: builtins.int
    DEVICE_ID_FIELD_NUMBER: builtins.int
    TAGS_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    topic: typing.Text = ...
    message_format: typing.Text = ...
    io_type: global___Component.IOType.V = ...
    device_id: typing.Text = ...
    @property
    def tags(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    description: typing.Text = ...
    id: typing.Text = ...
    name: typing.Text = ...
    def __init__(self,
        *,
        topic : typing.Text = ...,
        message_format : typing.Text = ...,
        io_type : global___Component.IOType.V = ...,
        device_id : typing.Text = ...,
        tags : typing.Optional[typing.Iterable[typing.Text]] = ...,
        description : typing.Text = ...,
        id : typing.Text = ...,
        name : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["description",b"description","device_id",b"device_id","id",b"id","io_type",b"io_type","message_format",b"message_format","name",b"name","tags",b"tags","topic",b"topic"]) -> None: ...
global___Component = Component

class ComponentList(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ELEMENTS_FIELD_NUMBER: builtins.int
    @property
    def elements(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Component]: ...
    def __init__(self,
        *,
        elements : typing.Optional[typing.Iterable[global___Component]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["elements",b"elements"]) -> None: ...
global___ComponentList = ComponentList
