"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions
import ubii.proto.devices.component_pb2

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class Device(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class DeviceType(_DeviceType, metaclass=_DeviceTypeEnumTypeWrapper):
        pass
    class _DeviceType:
        V = typing.NewType('V', builtins.int)
    class _DeviceTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_DeviceType.V], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        PARTICIPANT = Device.DeviceType.V(0)
        WATCHER = Device.DeviceType.V(1)

    PARTICIPANT = Device.DeviceType.V(0)
    WATCHER = Device.DeviceType.V(1)

    ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    DEVICE_TYPE_FIELD_NUMBER: builtins.int
    COMPONENTS_FIELD_NUMBER: builtins.int
    CLIENT_ID_FIELD_NUMBER: builtins.int
    TAGS_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    id: typing.Text = ...
    name: typing.Text = ...
    device_type: global___Device.DeviceType.V = ...
    @property
    def components(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[ubii.proto.devices.component_pb2.Component]: ...
    client_id: typing.Text = ...
    @property
    def tags(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    description: typing.Text = ...
    def __init__(self,
        *,
        id : typing.Text = ...,
        name : typing.Text = ...,
        device_type : global___Device.DeviceType.V = ...,
        components : typing.Optional[typing.Iterable[ubii.proto.devices.component_pb2.Component]] = ...,
        client_id : typing.Text = ...,
        tags : typing.Optional[typing.Iterable[typing.Text]] = ...,
        description : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["client_id",b"client_id","components",b"components","description",b"description","device_type",b"device_type","id",b"id","name",b"name","tags",b"tags"]) -> None: ...
global___Device = Device

class DeviceList(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ELEMENTS_FIELD_NUMBER: builtins.int
    @property
    def elements(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Device]: ...
    def __init__(self,
        *,
        elements : typing.Optional[typing.Iterable[global___Device]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["elements",b"elements"]) -> None: ...
global___DeviceList = DeviceList
