"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import proto
import proto.message

class TopicDemux(proto.message.Message):
    id = proto.Field(proto.STRING, number=0)
    name = proto.Field(proto.STRING, number=1)
    data_type = proto.Field(proto.STRING, number=2)
    output_topic_format = proto.Field(proto.STRING, number=3)

class TopicDemuxList(proto.message.Message):
    elements = proto.RepeatedField(TopicDemux, number=0)
