"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class TopicDemux(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    DATA_TYPE_FIELD_NUMBER: builtins.int
    OUTPUT_TOPIC_FORMAT_FIELD_NUMBER: builtins.int
    id: typing.Text = ...
    name: typing.Text = ...
    data_type: typing.Text = ...
    output_topic_format: typing.Text = ...
    def __init__(self,
        *,
        id : typing.Text = ...,
        name : typing.Text = ...,
        data_type : typing.Text = ...,
        output_topic_format : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["data_type",b"data_type","id",b"id","name",b"name","output_topic_format",b"output_topic_format"]) -> None: ...
global___TopicDemux = TopicDemux

class TopicDemuxList(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ELEMENTS_FIELD_NUMBER: builtins.int
    @property
    def elements(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TopicDemux]: ...
    def __init__(self,
        *,
        elements : typing.Optional[typing.Iterable[global___TopicDemux]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["elements",b"elements"]) -> None: ...
global___TopicDemuxList = TopicDemuxList
