"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import proto
import proto.message

class ProcessingMode(proto.message.Message):
    class Frequency(proto.message.Message):
        hertz = proto.Field(proto.INT32, number=0)

    class Lockstep(proto.message.Message):
        process_request_endpoint = proto.Field(proto.STRING, number=0)

    class TriggerOnInput(proto.message.Message):
        min_delay_ms = proto.Field(proto.INT32, number=0)
        all_inputs_need_update = proto.Field(proto.BOOL, number=1)

    frequency = proto.Field(Frequency, number=0)
    lockstep = proto.Field(Lockstep, number=1)
    trigger_on_input = proto.Field(TriggerOnInput, number=2)

class ModuleIO(proto.message.Message):
    internal_name = proto.Field(proto.STRING, number=0)
    message_format = proto.Field(proto.STRING, number=1)

class ProcessingModule(proto.message.Message):
    class Status(proto.Enum):
        INITIALIZED = 0
        CREATED = 1
        PROCESSING = 2
        HALTED = 3
        DESTROYED = 4

    class Language(proto.Enum):
        CPP = 0
        PY = 1
        JS = 2
        CS = 3
        JAVA = 4

    id = proto.Field(proto.STRING, number=0)
    name = proto.Field(proto.STRING, number=1)
    authors = proto.RepeatedField(proto.STRING, number=2)
    tags = proto.RepeatedField(proto.STRING, number=3)
    description = proto.Field(proto.STRING, number=4)
    node_id = proto.Field(proto.STRING, number=5)
    session_id = proto.Field(proto.STRING, number=6)
    status = proto.Field(Status, number=7)
    processing_mode = proto.Field(ProcessingMode, number=8)
    inputs = proto.RepeatedField(ModuleIO, number=9)
    outputs = proto.RepeatedField(ModuleIO, number=10)
    language = proto.Field(Language, number=11)
    on_processing_stringified = proto.Field(proto.STRING, number=12)
    on_created_stringified = proto.Field(proto.STRING, number=13)
    on_halted_stringified = proto.Field(proto.STRING, number=14)
    on_destroyed_stringified = proto.Field(proto.STRING, number=15)

class ProcessingModuleList(proto.message.Message):
    elements = proto.RepeatedField(ProcessingModule, number=0)
