# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ubii/proto_baseline/dataStructure/buttonEventType.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7ubii/proto_baseline/dataStructure/buttonEventType.proto\x12!ubii.proto_baseline.dataStructure*#\n\x0f\x42uttonEventType\x12\x06\n\x02UP\x10\x00\x12\x08\n\x04\x44OWN\x10\x01\x62\x06proto3')

_BUTTONEVENTTYPE = DESCRIPTOR.enum_types_by_name['ButtonEventType']
ButtonEventType = enum_type_wrapper.EnumTypeWrapper(_BUTTONEVENTTYPE)
UP = 0
DOWN = 1


if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BUTTONEVENTTYPE._serialized_start=94
  _BUTTONEVENTTYPE._serialized_end=129
# @@protoc_insertion_point(module_scope)
