# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ubii/proto_baseline/dataStructure/handGestureType.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7ubii/proto_baseline/dataStructure/handGestureType.proto\x12!ubii.proto_baseline.dataStructure*d\n\x0fHandGestureType\x12\x08\n\x04REST\x10\x00\x12\x12\n\x0e\x46INGERS_SPREAD\x10\x01\x12\x0b\n\x07WAVE_IN\x10\x02\x12\x0c\n\x08WAVE_OUT\x10\x03\x12\x08\n\x04\x46IST\x10\x04\x12\x0e\n\nDOUBLE_TAP\x10\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ubii.proto_baseline.dataStructure.handGestureType_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HANDGESTURETYPE._serialized_start=94
  _HANDGESTURETYPE._serialized_end=194
# @@protoc_insertion_point(module_scope)
