# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ubii/proto_baseline/dataStructure/keyEvent.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ubii.proto_baseline.dataStructure import buttonEventType_pb2 as ubii_dot_proto__baseline_dot_dataStructure_dot_buttonEventType__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0ubii/proto_baseline/dataStructure/keyEvent.proto\x12!ubii.proto_baseline.dataStructure\x1a\x37ubii/proto_baseline/dataStructure/buttonEventType.proto\"Y\n\x08KeyEvent\x12@\n\x04type\x18\x01 \x01(\x0e\x32\x32.ubii.proto_baseline.dataStructure.ButtonEventType\x12\x0b\n\x03key\x18\x02 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ubii.proto_baseline.dataStructure.keyEvent_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _KEYEVENT._serialized_start=144
  _KEYEVENT._serialized_end=233
# @@protoc_insertion_point(module_scope)
