# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ubii/proto_baseline/dataStructure/lists.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-ubii/proto_baseline/dataStructure/lists.proto\x12!ubii.proto_baseline.dataStructure\"\x1e\n\nStringList\x12\x10\n\x08\x65lements\x18\x01 \x03(\t\"\x1e\n\nDoubleList\x12\x10\n\x08\x65lements\x18\x01 \x03(\x01\"\x1d\n\tFloatList\x12\x10\n\x08\x65lements\x18\x01 \x03(\x02\"\x1c\n\x08\x42oolList\x12\x10\n\x08\x65lements\x18\x01 \x03(\x08\"\x1d\n\tInt32List\x12\x10\n\x08\x65lements\x18\x01 \x03(\x05\x62\x06proto3')



_STRINGLIST = DESCRIPTOR.message_types_by_name['StringList']
_DOUBLELIST = DESCRIPTOR.message_types_by_name['DoubleList']
_FLOATLIST = DESCRIPTOR.message_types_by_name['FloatList']
_BOOLLIST = DESCRIPTOR.message_types_by_name['BoolList']
_INT32LIST = DESCRIPTOR.message_types_by_name['Int32List']
StringList = _reflection.GeneratedProtocolMessageType('StringList', (_message.Message,), {
  'DESCRIPTOR' : _STRINGLIST,
  '__module__' : 'ubii.proto_baseline.dataStructure.lists_pb2'
  # @@protoc_insertion_point(class_scope:ubii.proto_baseline.dataStructure.StringList)
  })
_sym_db.RegisterMessage(StringList)

DoubleList = _reflection.GeneratedProtocolMessageType('DoubleList', (_message.Message,), {
  'DESCRIPTOR' : _DOUBLELIST,
  '__module__' : 'ubii.proto_baseline.dataStructure.lists_pb2'
  # @@protoc_insertion_point(class_scope:ubii.proto_baseline.dataStructure.DoubleList)
  })
_sym_db.RegisterMessage(DoubleList)

FloatList = _reflection.GeneratedProtocolMessageType('FloatList', (_message.Message,), {
  'DESCRIPTOR' : _FLOATLIST,
  '__module__' : 'ubii.proto_baseline.dataStructure.lists_pb2'
  # @@protoc_insertion_point(class_scope:ubii.proto_baseline.dataStructure.FloatList)
  })
_sym_db.RegisterMessage(FloatList)

BoolList = _reflection.GeneratedProtocolMessageType('BoolList', (_message.Message,), {
  'DESCRIPTOR' : _BOOLLIST,
  '__module__' : 'ubii.proto_baseline.dataStructure.lists_pb2'
  # @@protoc_insertion_point(class_scope:ubii.proto_baseline.dataStructure.BoolList)
  })
_sym_db.RegisterMessage(BoolList)

Int32List = _reflection.GeneratedProtocolMessageType('Int32List', (_message.Message,), {
  'DESCRIPTOR' : _INT32LIST,
  '__module__' : 'ubii.proto_baseline.dataStructure.lists_pb2'
  # @@protoc_insertion_point(class_scope:ubii.proto_baseline.dataStructure.Int32List)
  })
_sym_db.RegisterMessage(Int32List)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STRINGLIST._serialized_start=84
  _STRINGLIST._serialized_end=114
  _DOUBLELIST._serialized_start=116
  _DOUBLELIST._serialized_end=146
  _FLOATLIST._serialized_start=148
  _FLOATLIST._serialized_end=177
  _BOOLLIST._serialized_start=179
  _BOOLLIST._serialized_end=207
  _INT32LIST._serialized_start=209
  _INT32LIST._serialized_end=238
# @@protoc_insertion_point(module_scope)
