# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ubii/proto_baseline/dataStructure/matrix3x2.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1ubii/proto_baseline/dataStructure/matrix3x2.proto\x12!ubii.proto_baseline.dataStructure\"Y\n\tMatrix3x2\x12\x0b\n\x03m00\x18\x01 \x01(\x01\x12\x0b\n\x03m01\x18\x02 \x01(\x01\x12\x0b\n\x03m10\x18\x03 \x01(\x01\x12\x0b\n\x03m11\x18\x04 \x01(\x01\x12\x0b\n\x03m20\x18\x05 \x01(\x01\x12\x0b\n\x03m21\x18\x06 \x01(\x01\x62\x06proto3')



_MATRIX3X2 = DESCRIPTOR.message_types_by_name['Matrix3x2']
Matrix3x2 = _reflection.GeneratedProtocolMessageType('Matrix3x2', (_message.Message,), {
  'DESCRIPTOR' : _MATRIX3X2,
  '__module__' : 'ubii.proto_baseline.dataStructure.matrix3x2_pb2'
  # @@protoc_insertion_point(class_scope:ubii.proto_baseline.dataStructure.Matrix3x2)
  })
_sym_db.RegisterMessage(Matrix3x2)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MATRIX3X2._serialized_start=88
  _MATRIX3X2._serialized_end=177
# @@protoc_insertion_point(module_scope)
