# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ubii/proto_baseline/dataStructure/myoEvent.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ubii.proto_baseline.dataStructure import vector8_pb2 as ubii_dot_proto__baseline_dot_dataStructure_dot_vector8__pb2
from ubii.proto_baseline.dataStructure import vector3_pb2 as ubii_dot_proto__baseline_dot_dataStructure_dot_vector3__pb2
from ubii.proto_baseline.dataStructure import quaternion_pb2 as ubii_dot_proto__baseline_dot_dataStructure_dot_quaternion__pb2
from ubii.proto_baseline.dataStructure import handGestureType_pb2 as ubii_dot_proto__baseline_dot_dataStructure_dot_handGestureType__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0ubii/proto_baseline/dataStructure/myoEvent.proto\x12!ubii.proto_baseline.dataStructure\x1a/ubii/proto_baseline/dataStructure/vector8.proto\x1a/ubii/proto_baseline/dataStructure/vector3.proto\x1a\x32ubii/proto_baseline/dataStructure/quaternion.proto\x1a\x37ubii/proto_baseline/dataStructure/handGestureType.proto\"\xce\x02\n\x08MyoEvent\x12\x37\n\x03\x65mg\x18\x01 \x01(\x0b\x32*.ubii.proto_baseline.dataStructure.Vector8\x12\x42\n\x0borientation\x18\x02 \x01(\x0b\x32-.ubii.proto_baseline.dataStructure.Quaternion\x12=\n\tgyroscope\x18\x03 \x01(\x0b\x32*.ubii.proto_baseline.dataStructure.Vector3\x12\x41\n\raccelerometer\x18\x04 \x01(\x0b\x32*.ubii.proto_baseline.dataStructure.Vector3\x12\x43\n\x07gesture\x18\x05 \x01(\x0e\x32\x32.ubii.proto_baseline.dataStructure.HandGestureTypeb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ubii.proto_baseline.dataStructure.myoEvent_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MYOEVENT._serialized_start=295
  _MYOEVENT._serialized_end=629
# @@protoc_insertion_point(module_scope)
