# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ubii/proto_baseline/dataStructure/pose2d.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ubii.proto_baseline.dataStructure import vector2_pb2 as ubii_dot_proto__baseline_dot_dataStructure_dot_vector2__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.ubii/proto_baseline/dataStructure/pose2d.proto\x12!ubii.proto_baseline.dataStructure\x1a/ubii/proto_baseline/dataStructure/vector2.proto\"\xa7\x01\n\x06Pose2D\x12<\n\x08position\x18\x01 \x01(\x0b\x32*.ubii.proto_baseline.dataStructure.Vector2\x12?\n\tdirection\x18\x02 \x01(\x0b\x32*.ubii.proto_baseline.dataStructure.Vector2H\x00\x12\x0f\n\x05\x61ngle\x18\x03 \x01(\x02H\x00\x42\r\n\x0borientationb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ubii.proto_baseline.dataStructure.pose2d_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _POSE2D._serialized_start=135
  _POSE2D._serialized_end=302
# @@protoc_insertion_point(module_scope)
