# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ubii/proto_baseline/dataStructure/quaternion.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2ubii/proto_baseline/dataStructure/quaternion.proto\x12!ubii.proto_baseline.dataStructure\"8\n\nQuaternion\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x12\t\n\x01w\x18\x04 \x01(\x01\"Q\n\x0eQuaternionList\x12?\n\x08\x65lements\x18\x01 \x03(\x0b\x32-.ubii.proto_baseline.dataStructure.Quaternionb\x06proto3')



_QUATERNION = DESCRIPTOR.message_types_by_name['Quaternion']
_QUATERNIONLIST = DESCRIPTOR.message_types_by_name['QuaternionList']
Quaternion = _reflection.GeneratedProtocolMessageType('Quaternion', (_message.Message,), {
  'DESCRIPTOR' : _QUATERNION,
  '__module__' : 'ubii.proto_baseline.dataStructure.quaternion_pb2'
  # @@protoc_insertion_point(class_scope:ubii.proto_baseline.dataStructure.Quaternion)
  })
_sym_db.RegisterMessage(Quaternion)

QuaternionList = _reflection.GeneratedProtocolMessageType('QuaternionList', (_message.Message,), {
  'DESCRIPTOR' : _QUATERNIONLIST,
  '__module__' : 'ubii.proto_baseline.dataStructure.quaternion_pb2'
  # @@protoc_insertion_point(class_scope:ubii.proto_baseline.dataStructure.QuaternionList)
  })
_sym_db.RegisterMessage(QuaternionList)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _QUATERNION._serialized_start=89
  _QUATERNION._serialized_end=145
  _QUATERNIONLIST._serialized_start=147
  _QUATERNIONLIST._serialized_end=228
# @@protoc_insertion_point(module_scope)
