# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ubii/proto_baseline/dataStructure/vector8.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/ubii/proto_baseline/dataStructure/vector8.proto\x12!ubii.proto_baseline.dataStructure\"i\n\x07Vector8\x12\n\n\x02v0\x18\x01 \x01(\x01\x12\n\n\x02v1\x18\x02 \x01(\x01\x12\n\n\x02v2\x18\x03 \x01(\x01\x12\n\n\x02v3\x18\x04 \x01(\x01\x12\n\n\x02v4\x18\x05 \x01(\x01\x12\n\n\x02v5\x18\x06 \x01(\x01\x12\n\n\x02v6\x18\x07 \x01(\x01\x12\n\n\x02v7\x18\x08 \x01(\x01\"K\n\x0bVector8List\x12<\n\x08\x65lements\x18\x01 \x03(\x0b\x32*.ubii.proto_baseline.dataStructure.Vector8b\x06proto3')



_VECTOR8 = DESCRIPTOR.message_types_by_name['Vector8']
_VECTOR8LIST = DESCRIPTOR.message_types_by_name['Vector8List']
Vector8 = _reflection.GeneratedProtocolMessageType('Vector8', (_message.Message,), {
  'DESCRIPTOR' : _VECTOR8,
  '__module__' : 'ubii.proto_baseline.dataStructure.vector8_pb2'
  # @@protoc_insertion_point(class_scope:ubii.proto_baseline.dataStructure.Vector8)
  })
_sym_db.RegisterMessage(Vector8)

Vector8List = _reflection.GeneratedProtocolMessageType('Vector8List', (_message.Message,), {
  'DESCRIPTOR' : _VECTOR8LIST,
  '__module__' : 'ubii.proto_baseline.dataStructure.vector8_pb2'
  # @@protoc_insertion_point(class_scope:ubii.proto_baseline.dataStructure.Vector8List)
  })
_sym_db.RegisterMessage(Vector8List)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VECTOR8._serialized_start=86
  _VECTOR8._serialized_end=191
  _VECTOR8LIST._serialized_start=193
  _VECTOR8LIST._serialized_end=268
# @@protoc_insertion_point(module_scope)
