# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ubii/proto_baseline/dataStructure/vector4.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/ubii/proto_baseline/dataStructure/vector4.proto\x12!ubii.proto_baseline.dataStructure\"5\n\x07Vector4\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x12\t\n\x01w\x18\x04 \x01(\x01\"K\n\x0bVector4List\x12<\n\x08\x65lements\x18\x01 \x03(\x0b\x32*.ubii.proto_baseline.dataStructure.Vector4b\x06proto3')



_VECTOR4 = DESCRIPTOR.message_types_by_name['Vector4']
_VECTOR4LIST = DESCRIPTOR.message_types_by_name['Vector4List']
Vector4 = _reflection.GeneratedProtocolMessageType('Vector4', (_message.Message,), {
  'DESCRIPTOR' : _VECTOR4,
  '__module__' : 'ubii.proto_baseline.dataStructure.vector4_pb2'
  # @@protoc_insertion_point(class_scope:ubii.proto_baseline.dataStructure.Vector4)
  })
_sym_db.RegisterMessage(Vector4)

Vector4List = _reflection.GeneratedProtocolMessageType('Vector4List', (_message.Message,), {
  'DESCRIPTOR' : _VECTOR4LIST,
  '__module__' : 'ubii.proto_baseline.dataStructure.vector4_pb2'
  # @@protoc_insertion_point(class_scope:ubii.proto_baseline.dataStructure.Vector4List)
  })
_sym_db.RegisterMessage(Vector4List)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VECTOR4._serialized_start=86
  _VECTOR4._serialized_end=139
  _VECTOR4LIST._serialized_start=141
  _VECTOR4LIST._serialized_end=216
# @@protoc_insertion_point(module_scope)
