# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ubii/proto_baseline/topicData/topicData.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ubii.proto_baseline.topicData import topicDataRecord_pb2 as ubii_dot_proto__baseline_dot_topicData_dot_topicDataRecord__pb2
from ubii.proto_baseline.general import error_pb2 as ubii_dot_proto__baseline_dot_general_dot_error__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-ubii/proto_baseline/topicData/topicData.proto\x12\x1dubii.proto_baseline.topicData\x1a\x33ubii/proto_baseline/topicData/topicDataRecord.proto\x1a\'ubii/proto_baseline/general/error.proto\"\xeb\x01\n\tTopicData\x12K\n\x11topic_data_record\x18\x02 \x01(\x0b\x32..ubii.proto_baseline.topicData.TopicDataRecordH\x00\x12T\n\x16topic_data_record_list\x18\x03 \x01(\x0b\x32\x32.ubii.proto_baseline.topicData.TopicDataRecordListH\x00\x12\x33\n\x05\x65rror\x18\x04 \x01(\x0b\x32\".ubii.proto_baseline.general.ErrorH\x00\x42\x06\n\x04typeb\x06proto3')



_TOPICDATA = DESCRIPTOR.message_types_by_name['TopicData']
TopicData = _reflection.GeneratedProtocolMessageType('TopicData', (_message.Message,), {
  'DESCRIPTOR' : _TOPICDATA,
  '__module__' : 'ubii.proto_baseline.topicData.topicData_pb2'
  # @@protoc_insertion_point(class_scope:ubii.proto_baseline.topicData.TopicData)
  })
_sym_db.RegisterMessage(TopicData)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TOPICDATA._serialized_start=175
  _TOPICDATA._serialized_end=410
# @@protoc_insertion_point(module_scope)
