"""
@generated by codestare-proto-plus.  Do not edit manually!
isort:skip_file
"""
import proto
from proto import (
    Field,
    RepeatedField,
    STRING,
)

from proto.message import (
    Message,
)


__protobuf__ = proto.module(
    package="ubii.interact.v1",
    manifest={
        "Error",
        "ErrorList",
    }
)


class Error(Message):
    title = Field(
        STRING,
        number=1,
    )
    message = Field(
        STRING,
        number=2,
    )
    stack = Field(
        STRING,
        number=3,
    )



class ErrorList(Message):
    elements = RepeatedField(
        Error,
        number=1,
    )


