"""
@generated by codestare-proto-plus.  Do not edit manually!
"""
import proto
from proto import (
    Field,
)

from proto.message import (
    Message,
)

from ubii.proto.v1.types.general.error_pb_plus import (
    Error,
)

from ubii.proto.v1.types.topicData.topicDataRecord_pb_plus import (
    TopicDataRecord,
    TopicDataRecordList,
)


__protobuf__ = proto.module(
    package="ubii.proto.v1",
    manifest={
        "TopicData",
    }
)


class TopicData(Message):
    """Generated from ubii/proto/v1/types/topicData/topicData.proto

    Attributes:
        topic_data_record (:obj:`Field`): :obj:`Field` of type :obj:`TopicDataRecord`
        topic_data_record_list (:obj:`Field`): :obj:`Field` of type :obj:`TopicDataRecordList`
        error (:obj:`Field`): :obj:`Field` of type :obj:`Error`

    """
    topic_data_record = Field(
        TopicDataRecord,
        number=2,
        oneof='type',
    )
    topic_data_record_list = Field(
        TopicDataRecordList,
        number=3,
        oneof='type',
    )
    error = Field(
        Error,
        number=4,
        oneof='type',
    )

