"""
@generated by codestare-proto-plus.  Do not edit manually!
"""
from builtins import (
    int,
    str,
)

from proto import (
    Field,
    INT32,
    MESSAGE,
    RepeatedField,
    STRING,
    module,
)

from proto.message import (
    Message,
)

from typing import (
    Iterable,
)

from ubii.proto.v1.topicData.topicDataRecord_pb_plus import (
    TopicDataRecord,
)


__protobuf__ = module(
    package="ubii.proto.v1.processing",
    marshal="ubii.proto.v1",
    manifest={
        "LockstepProcessingRequest",
        "LockstepProcessingReply",
    }
)


class LockstepProcessingRequest(Message):
    """
    Attributes:
        processing_module_ids (proto.fields.RepeatedField): :obj:`~proto.fields.RepeatedField` of type
            :obj:`~proto.primitives.ProtoType.STRING`
        records (proto.fields.RepeatedField): :obj:`~proto.fields.RepeatedField` of type
            :obj:`~ubii.proto.v1.topicData.topicDataRecord_pb_plus.TopicDataRecord`
        delta_time_ms (proto.fields.Field): :obj:`~proto.fields.Field` of type
            :obj:`~proto.primitives.ProtoType.INT32`
    """

    processing_module_ids: Iterable[str] = RepeatedField(
        STRING,
        number=1,
    )
    records: Iterable[TopicDataRecord] = RepeatedField(
        MESSAGE,
        number=2,
        message=TopicDataRecord,
    )
    delta_time_ms: int = Field(
        INT32,
        number=3,
    )


class LockstepProcessingReply(Message):
    """
    Attributes:
        processing_module_ids (proto.fields.RepeatedField): :obj:`~proto.fields.RepeatedField` of type
            :obj:`~proto.primitives.ProtoType.STRING`
        records (proto.fields.RepeatedField): :obj:`~proto.fields.RepeatedField` of type
            :obj:`~ubii.proto.v1.topicData.topicDataRecord_pb_plus.TopicDataRecord`
    """

    processing_module_ids: Iterable[str] = RepeatedField(
        STRING,
        number=1,
    )
    records: Iterable[TopicDataRecord] = RepeatedField(
        MESSAGE,
        number=2,
        message=TopicDataRecord,
    )

