"""
@generated by codestare-proto-plus.  Do not edit manually!
"""
from proto import (
    Field,
    RepeatedField,
    STRING,
    module,
)

from proto.message import (
    Message,
)


__protobuf__ = module(
    package="ubii.proto.v1",
    manifest={
        "Service",
        "ServiceList",
    }
)


class Service(Message):
    """Generated from ubii/proto/v1/services/service.proto

    Attributes:
        topic (proto.fields.Field): :obj:`~proto.fields.Field` of type
             :obj:`~proto.STRING`
        request_message_format (proto.fields.Field): :obj:`~proto.fields.Field` of type
             :obj:`~proto.STRING`
        response_message_format (proto.fields.Field): :obj:`~proto.fields.Field` of
             type :obj:`~proto.STRING`
        tags (proto.fields.RepeatedField): :obj:`~proto.fields.RepeatedField` of type
             :obj:`~proto.STRING`
        description (proto.fields.Field): :obj:`~proto.fields.Field` of type
             :obj:`~proto.STRING`

    """
    topic = Field(
        STRING,
        number=1,
    )
    request_message_format = Field(
        STRING,
        number=2,
    )
    response_message_format = Field(
        STRING,
        number=3,
    )
    tags = RepeatedField(
        STRING,
        number=4,
    )
    description = Field(
        STRING,
        number=5,
    )


class ServiceList(Message):
    """Generated from ubii/proto/v1/services/service.proto

    Attributes:
        elements (proto.fields.RepeatedField): :obj:`~proto.fields.RepeatedField` of
             type :obj:`~.Service`

    """
    elements = RepeatedField(
        Service,
        number=1,
    )

