"""
@generated by codestare-proto-plus.  Do not edit manually!
"""
import proto
from proto import (
    Field,
    RepeatedField,
    STRING,
)

from proto.message import (
    Message,
)


__protobuf__ = proto.module(
    package="ubii.proto.v1",
    manifest={
        "TopicSubscription",
    }
)


class TopicSubscription(Message):
    """Generated from ubii/proto/v1/types/services/request/topicSubscription.proto

    Attributes:
        client_id (:obj:`Field`): :obj:`Field` of type :obj:`STRING`
        subscribe_topics (:obj:`RepeatedField`): :obj:`RepeatedField` of type :obj:`STRING`
        unsubscribe_topics (:obj:`RepeatedField`): :obj:`RepeatedField` of type :obj:`STRING`
        subscribe_topic_regexp (:obj:`RepeatedField`): :obj:`RepeatedField` of type :obj:`STRING`
        unsubscribe_topic_regexp (:obj:`RepeatedField`): :obj:`RepeatedField` of type :obj:`STRING`

    """
    client_id = Field(
        STRING,
        number=1,
    )
    subscribe_topics = RepeatedField(
        STRING,
        number=2,
    )
    unsubscribe_topics = RepeatedField(
        STRING,
        number=3,
    )
    subscribe_topic_regexp = RepeatedField(
        STRING,
        number=4,
    )
    unsubscribe_topic_regexp = RepeatedField(
        STRING,
        number=5,
    )

