"""
@generated by codestare-proto-plus.  Do not edit manually!
"""
import proto
from proto import (
    Field,
    STRING,
)

from proto.message import (
    Message,
)


__protobuf__ = proto.module(
    package="ubii.proto.v1",
    manifest={
        "Server",
    }
)


class Server(Message):
    """Generated from ubii/proto/v1/types/servers/server.proto

    Attributes:
        id (:obj:`Field`): :obj:`Field` of type :obj:`STRING`
        name (:obj:`Field`): :obj:`Field` of type :obj:`STRING`
        ip_ethernet (:obj:`Field`): :obj:`Field` of type :obj:`STRING`
        ip_wlan (:obj:`Field`): :obj:`Field` of type :obj:`STRING`
        port_service_zmq (:obj:`Field`): :obj:`Field` of type :obj:`STRING`
        port_service_rest (:obj:`Field`): :obj:`Field` of type :obj:`STRING`
        port_topic_data_zmq (:obj:`Field`): :obj:`Field` of type :obj:`STRING`
        port_topic_data_ws (:obj:`Field`): :obj:`Field` of type :obj:`STRING`
        constants_json (:obj:`Field`): :obj:`Field` of type :obj:`STRING`

    """
    id = Field(
        STRING,
        number=1,
    )
    name = Field(
        STRING,
        number=2,
    )
    ip_ethernet = Field(
        STRING,
        number=3,
    )
    ip_wlan = Field(
        STRING,
        number=4,
    )
    port_service_zmq = Field(
        STRING,
        number=5,
    )
    port_service_rest = Field(
        STRING,
        number=6,
    )
    port_topic_data_zmq = Field(
        STRING,
        number=7,
    )
    port_topic_data_ws = Field(
        STRING,
        number=8,
    )
    constants_json = Field(
        STRING,
        number=9,
    )

