"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import proto

class HandGestureType(proto.Enum):
    REST = 0
    FINGERS_SPREAD = 1
    WAVE_IN = 2
    WAVE_OUT = 3
    FIST = 4
    DOUBLE_TAP = 5
