"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import proto
import proto.message

class Image2D(proto.message.Message):
    class DataFormat(proto.Enum):
        GRAY8 = 0
        RGB8 = 1
        RGBA8 = 2

    width = proto.Field(proto.INT32, number=0)
    height = proto.Field(proto.INT32, number=1)
    data_format = proto.Field(DataFormat, number=2)
    data = proto.Field(proto.BYTES, number=3)

class Image2DList(proto.message.Message):
    elements = proto.RepeatedField(Image2D, number=0)
