"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class Image2D(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class DataFormat(_DataFormat, metaclass=_DataFormatEnumTypeWrapper):
        pass
    class _DataFormat:
        V = typing.NewType('V', builtins.int)
    class _DataFormatEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_DataFormat.V], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        GRAY8 = Image2D.DataFormat.V(0)
        RGB8 = Image2D.DataFormat.V(1)
        RGBA8 = Image2D.DataFormat.V(2)

    GRAY8 = Image2D.DataFormat.V(0)
    RGB8 = Image2D.DataFormat.V(1)
    RGBA8 = Image2D.DataFormat.V(2)

    WIDTH_FIELD_NUMBER: builtins.int
    HEIGHT_FIELD_NUMBER: builtins.int
    DATA_FORMAT_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    width: builtins.int = ...
    height: builtins.int = ...
    data_format: global___Image2D.DataFormat.V = ...
    data: builtins.bytes = ...
    def __init__(self,
        *,
        width : builtins.int = ...,
        height : builtins.int = ...,
        data_format : global___Image2D.DataFormat.V = ...,
        data : builtins.bytes = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["data",b"data","data_format",b"data_format","height",b"height","width",b"width"]) -> None: ...
global___Image2D = Image2D

class Image2DList(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ELEMENTS_FIELD_NUMBER: builtins.int
    @property
    def elements(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Image2D]: ...
    def __init__(self,
        *,
        elements : typing.Optional[typing.Iterable[global___Image2D]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["elements",b"elements"]) -> None: ...
global___Image2DList = Image2DList
