"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import proto
import proto.message

class Matrix3x2(proto.message.Message):
    m00 = proto.Field(proto.DOUBLE, number=0)
    m01 = proto.Field(proto.DOUBLE, number=1)
    m10 = proto.Field(proto.DOUBLE, number=2)
    m11 = proto.Field(proto.DOUBLE, number=3)
    m20 = proto.Field(proto.DOUBLE, number=4)
    m21 = proto.Field(proto.DOUBLE, number=5)
