"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class Matrix3x2(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    M00_FIELD_NUMBER: builtins.int
    M01_FIELD_NUMBER: builtins.int
    M10_FIELD_NUMBER: builtins.int
    M11_FIELD_NUMBER: builtins.int
    M20_FIELD_NUMBER: builtins.int
    M21_FIELD_NUMBER: builtins.int
    m00: builtins.float = ...
    m01: builtins.float = ...
    m10: builtins.float = ...
    m11: builtins.float = ...
    m20: builtins.float = ...
    m21: builtins.float = ...
    def __init__(self,
        *,
        m00 : builtins.float = ...,
        m01 : builtins.float = ...,
        m10 : builtins.float = ...,
        m11 : builtins.float = ...,
        m20 : builtins.float = ...,
        m21 : builtins.float = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["m00",b"m00","m01",b"m01","m10",b"m10","m11",b"m11","m20",b"m20","m21",b"m21"]) -> None: ...
global___Matrix3x2 = Matrix3x2
