"""
@generated by codestare-proto-plus.  Do not edit manually!
isort:skip_file
"""
import proto
import proto.message
import ubii.proto.dataStructure.buttonEventType_pb_plus

class MouseEvent(proto.message.Message):
    type = proto.Field(ubii.proto.dataStructure.buttonEventType_pb_plus.ButtonEventType, number=1)
    button = proto.Field(proto.INT32, number=2)
