"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import proto
import proto.message
import ubii.proto.dataStructure.handGestureType_pb_plus
import ubii.proto.dataStructure.quaternion_pb_plus
import ubii.proto.dataStructure.vector3_pb_plus
import ubii.proto.dataStructure.vector8_pb_plus

class MyoEvent(proto.message.Message):
    emg = proto.Field(ubii.proto.dataStructure.vector8_pb_plus.Vector8, number=0)
    orientation = proto.Field(ubii.proto.dataStructure.quaternion_pb_plus.Quaternion, number=1)
    gyroscope = proto.Field(ubii.proto.dataStructure.vector3_pb_plus.Vector3, number=2)
    accelerometer = proto.Field(ubii.proto.dataStructure.vector3_pb_plus.Vector3, number=3)
    gesture = proto.Field(ubii.proto.dataStructure.handGestureType_pb_plus.HandGestureType, number=4)
