"""
@generated by codestare-proto-plus.  Do not edit manually!
isort:skip_file
"""
import proto
import proto.message
import ubii.proto.dataStructure.pose2d_pb_plus
import ubii.proto.dataStructure.vector2_pb_plus


class Object2D(proto.message.Message):
    id = proto.Field(
        proto.STRING,
        number=1,
    )
    pose = proto.Field(
        ubii.proto.dataStructure.pose2d_pb_plus.Pose2D,
        number=2,
    )
    size = proto.Field(
        ubii.proto.dataStructure.vector2_pb_plus.Vector2,
        number=3,
    )
    user_data_json = proto.Field(
        proto.STRING,
        number=4,
    )


class Object2DList(proto.message.Message):
    elements = proto.RepeatedField(
        Object2D,
        number=1,
    )

