"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing
import typing_extensions
import ubii.proto.dataStructure.pose3d_pb2
import ubii.proto.dataStructure.vector3_pb2

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class Object3D(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ID_FIELD_NUMBER: builtins.int
    POSE_FIELD_NUMBER: builtins.int
    SIZE_FIELD_NUMBER: builtins.int
    USER_DATA_JSON_FIELD_NUMBER: builtins.int
    id: typing.Text = ...
    @property
    def pose(self) -> ubii.proto.dataStructure.pose3d_pb2.Pose3D: ...
    @property
    def size(self) -> ubii.proto.dataStructure.vector3_pb2.Vector3: ...
    user_data_json: typing.Text = ...
    def __init__(self,
        *,
        id : typing.Text = ...,
        pose : typing.Optional[ubii.proto.dataStructure.pose3d_pb2.Pose3D] = ...,
        size : typing.Optional[ubii.proto.dataStructure.vector3_pb2.Vector3] = ...,
        user_data_json : typing.Text = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["pose",b"pose","size",b"size"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["id",b"id","pose",b"pose","size",b"size","user_data_json",b"user_data_json"]) -> None: ...
global___Object3D = Object3D

class Object3DList(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ELEMENTS_FIELD_NUMBER: builtins.int
    @property
    def elements(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Object3D]: ...
    def __init__(self,
        *,
        elements : typing.Optional[typing.Iterable[global___Object3D]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["elements",b"elements"]) -> None: ...
global___Object3DList = Object3DList
