"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import proto
import proto.message
import ubii.proto.dataStructure.quaternion_pb_plus
import ubii.proto.dataStructure.vector3_pb_plus

class Pose3D(proto.message.Message):
    position = proto.Field(ubii.proto.dataStructure.vector3_pb_plus.Vector3, number=0)
    quaternion = proto.Field(ubii.proto.dataStructure.quaternion_pb_plus.Quaternion, number=1)
    euler = proto.Field(ubii.proto.dataStructure.vector3_pb_plus.Vector3, number=2)
