"""
@generated by codestare-proto-plus.  Do not edit manually!
isort:skip_file
"""
import proto
import proto.message

class Vector2(proto.message.Message):
    x = proto.Field(proto.DOUBLE, number=1)
    y = proto.Field(proto.DOUBLE, number=2)
