"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import proto
import proto.message

class Vector8(proto.message.Message):
    v0 = proto.Field(proto.DOUBLE, number=0)
    v1 = proto.Field(proto.DOUBLE, number=1)
    v2 = proto.Field(proto.DOUBLE, number=2)
    v3 = proto.Field(proto.DOUBLE, number=3)
    v4 = proto.Field(proto.DOUBLE, number=4)
    v5 = proto.Field(proto.DOUBLE, number=5)
    v6 = proto.Field(proto.DOUBLE, number=6)
    v7 = proto.Field(proto.DOUBLE, number=7)
