"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import proto
import proto.message

class Error(proto.message.Message):
    title = proto.Field(proto.STRING, number=0)
    message = proto.Field(proto.STRING, number=1)
    stack = proto.Field(proto.STRING, number=2)

class ErrorList(proto.message.Message):
    elements = proto.RepeatedField(Error, number=0)
