"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import proto
import proto.message

class Success(proto.message.Message):
    title = proto.Field(proto.STRING, number=0)
    message = proto.Field(proto.STRING, number=1)

class SuccessList(proto.message.Message):
    elements = proto.RepeatedField(Success, number=0)
