"""
@generated by codestare-proto-plus.  Do not edit manually!
"""
import proto
from proto import (
    BOOL,
    DOUBLE,
    FLOAT,
    INT32,
    RepeatedField,
    STRING,
)

from proto.message import (
    Message,
)


__protobuf__ = proto.module(
    package="ubii.proto.v1",
    manifest={
        "StringList",
        "DoubleList",
        "FloatList",
        "BoolList",
        "Int32List",
    }
)


class StringList(Message):
    """Generated from ubii/proto/v1/types/dataStructure/lists.proto

    Attributes:
        elements (:obj:`RepeatedField`): :obj:`RepeatedField` of type :obj:`STRING`

    """
    elements = RepeatedField(
        STRING,
        number=1,
    )


class DoubleList(Message):
    """Generated from ubii/proto/v1/types/dataStructure/lists.proto

    Attributes:
        elements (:obj:`RepeatedField`): :obj:`RepeatedField` of type :obj:`DOUBLE`

    """
    elements = RepeatedField(
        DOUBLE,
        number=1,
    )


class FloatList(Message):
    """Generated from ubii/proto/v1/types/dataStructure/lists.proto

    Attributes:
        elements (:obj:`RepeatedField`): :obj:`RepeatedField` of type :obj:`FLOAT`

    """
    elements = RepeatedField(
        FLOAT,
        number=1,
    )


class BoolList(Message):
    """Generated from ubii/proto/v1/types/dataStructure/lists.proto

    Attributes:
        elements (:obj:`RepeatedField`): :obj:`RepeatedField` of type :obj:`BOOL`

    """
    elements = RepeatedField(
        BOOL,
        number=1,
    )


class Int32List(Message):
    """Generated from ubii/proto/v1/types/dataStructure/lists.proto

    Attributes:
        elements (:obj:`RepeatedField`): :obj:`RepeatedField` of type :obj:`INT32`

    """
    elements = RepeatedField(
        INT32,
        number=1,
    )

