"""
@generated by codestare-proto-plus.  Do not edit manually!
"""
import proto
from proto import (
    DOUBLE,
    Field,
    RepeatedField,
)

from proto.message import (
    Message,
)


__protobuf__ = proto.module(
    package="ubii.proto.v1",
    manifest={
        "Quaternion",
        "QuaternionList",
    }
)


class Quaternion(Message):
    """Generated from ubii/proto/v1/types/dataStructure/quaternion.proto

    Attributes:
        x (:obj:`Field`): :obj:`Field` of type :obj:`DOUBLE`
        y (:obj:`Field`): :obj:`Field` of type :obj:`DOUBLE`
        z (:obj:`Field`): :obj:`Field` of type :obj:`DOUBLE`
        w (:obj:`Field`): :obj:`Field` of type :obj:`DOUBLE`

    """
    x = Field(
        DOUBLE,
        number=1,
    )
    y = Field(
        DOUBLE,
        number=2,
    )
    z = Field(
        DOUBLE,
        number=3,
    )
    w = Field(
        DOUBLE,
        number=4,
    )


class QuaternionList(Message):
    """Generated from ubii/proto/v1/types/dataStructure/quaternion.proto

    Attributes:
        elements (:obj:`RepeatedField`): :obj:`RepeatedField` of type :obj:`Quaternion`

    """
    elements = RepeatedField(
        Quaternion,
        number=1,
    )

