"""
@generated by codestare-proto-plus.  Do not edit manually!
"""
import proto
from proto import (
    Enum,
    FLOAT,
    Field,
    RepeatedField,
    STRING,
)

from proto.message import (
    Message,
)

from ubii.proto.v1.types.dataStructure.vector2_pb_plus import (
    Vector2,
)


__protobuf__ = proto.module(
    package="ubii.proto.v1",
    manifest={
        "TouchEvent",
        "TouchEventList",
    }
)


class TouchEvent(Message):
    """Generated from ubii/proto/v1/types/dataStructure/touchEvent.proto

    Attributes:
        type (:obj:`Field`): :obj:`Field` of type :obj:`TouchEventType`
        position (:obj:`Field`): :obj:`Field` of type :obj:`Vector2`
        id (:obj:`Field`): :obj:`Field` of type :obj:`STRING`
        force (:obj:`Field`): :obj:`Field` of type :obj:`FLOAT`

    """
    class TouchEventType(Enum):
        TOUCH_START = 0
        TOUCH_MOVE = 1
        TOUCH_END = 2

    type = Field(
        TouchEventType,
        number=1,
    )
    position = Field(
        Vector2,
        number=2,
    )
    id = Field(
        STRING,
        number=3,
    )
    force = Field(
        FLOAT,
        number=4,
    )


class TouchEventList(Message):
    """Generated from ubii/proto/v1/types/dataStructure/touchEvent.proto

    Attributes:
        elements (:obj:`RepeatedField`): :obj:`RepeatedField` of type :obj:`TouchEvent`

    """
    elements = RepeatedField(
        TouchEvent,
        number=1,
    )

