"""
@generated by codestare-proto-plus.  Do not edit manually!
"""
import proto
from proto import (
    DOUBLE,
    Field,
    RepeatedField,
)

from proto.message import (
    Message,
)


__protobuf__ = proto.module(
    package="ubii.proto.v1",
    manifest={
        "Vector3",
        "Vector3List",
    }
)


class Vector3(Message):
    """Generated from ubii/proto/v1/types/dataStructure/vector3.proto

    Attributes:
        x (:obj:`Field`): :obj:`Field` of type :obj:`DOUBLE`
        y (:obj:`Field`): :obj:`Field` of type :obj:`DOUBLE`
        z (:obj:`Field`): :obj:`Field` of type :obj:`DOUBLE`

    """
    x = Field(
        DOUBLE,
        number=1,
    )
    y = Field(
        DOUBLE,
        number=2,
    )
    z = Field(
        DOUBLE,
        number=3,
    )


class Vector3List(Message):
    """Generated from ubii/proto/v1/types/dataStructure/vector3.proto

    Attributes:
        elements (:obj:`RepeatedField`): :obj:`RepeatedField` of type :obj:`Vector3`

    """
    elements = RepeatedField(
        Vector3,
        number=1,
    )

