"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing
import typing_extensions
import ubii.proto.general.error_pb2
import ubii.proto.topicData.topicDataRecord_pb2

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class TopicData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    TOPIC_DATA_RECORD_FIELD_NUMBER: builtins.int
    TOPIC_DATA_RECORD_LIST_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    @property
    def topic_data_record(self) -> ubii.proto.topicData.topicDataRecord_pb2.TopicDataRecord: ...
    @property
    def topic_data_record_list(self) -> ubii.proto.topicData.topicDataRecord_pb2.TopicDataRecordList: ...
    @property
    def error(self) -> ubii.proto.general.error_pb2.Error: ...
    def __init__(self,
        *,
        topic_data_record : typing.Optional[ubii.proto.topicData.topicDataRecord_pb2.TopicDataRecord] = ...,
        topic_data_record_list : typing.Optional[ubii.proto.topicData.topicDataRecord_pb2.TopicDataRecordList] = ...,
        error : typing.Optional[ubii.proto.general.error_pb2.Error] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["error",b"error","topic_data_record",b"topic_data_record","topic_data_record_list",b"topic_data_record_list","type",b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["error",b"error","topic_data_record",b"topic_data_record","topic_data_record_list",b"topic_data_record_list","type",b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["type",b"type"]) -> typing.Optional[typing_extensions.Literal["topic_data_record","topic_data_record_list","error"]]: ...
global___TopicData = TopicData
