"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import proto
import proto.message
import ubii.proto.general.error_pb_plus
import ubii.proto.topicData.topicDataRecord_pb_plus

class TopicData(proto.message.Message):
    topic_data_record = proto.Field(ubii.proto.topicData.topicDataRecord_pb_plus.TopicDataRecord, number=0)
    topic_data_record_list = proto.Field(ubii.proto.topicData.topicDataRecord_pb_plus.TopicDataRecordList, number=1)
    error = proto.Field(ubii.proto.general.error_pb_plus.Error, number=2)
