"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import proto
import proto.message
import ubii.proto.dataStructure.color_pb_plus
import ubii.proto.dataStructure.image_pb_plus
import ubii.proto.dataStructure.keyEvent_pb_plus
import ubii.proto.dataStructure.lists_pb_plus
import ubii.proto.dataStructure.matrix3x2_pb_plus
import ubii.proto.dataStructure.matrix4x4_pb_plus
import ubii.proto.dataStructure.mouseEvent_pb_plus
import ubii.proto.dataStructure.myoEvent_pb_plus
import ubii.proto.dataStructure.object2d_pb_plus
import ubii.proto.dataStructure.object3d_pb_plus
import ubii.proto.dataStructure.pose2d_pb_plus
import ubii.proto.dataStructure.pose3d_pb_plus
import ubii.proto.dataStructure.quaternion_pb_plus
import ubii.proto.dataStructure.touchEvent_pb_plus
import ubii.proto.dataStructure.vector2_pb_plus
import ubii.proto.dataStructure.vector3_pb_plus
import ubii.proto.dataStructure.vector4_pb_plus
import ubii.proto.processing.processingModule_pb_plus
import ubii.proto.sessions.session_pb_plus
import ubii.proto.topicData.timestamp_pb_plus

class TopicDataRecord(proto.message.Message):
    topic = proto.Field(proto.STRING, number=0)
    timestamp = proto.Field(ubii.proto.topicData.timestamp_pb_plus.Timestamp, number=1)
    double = proto.Field(proto.DOUBLE, number=2)
    bool = proto.Field(proto.BOOL, number=3)
    string = proto.Field(proto.STRING, number=4)
    vector2 = proto.Field(ubii.proto.dataStructure.vector2_pb_plus.Vector2, number=5)
    vector3 = proto.Field(ubii.proto.dataStructure.vector3_pb_plus.Vector3, number=6)
    vector4 = proto.Field(ubii.proto.dataStructure.vector4_pb_plus.Vector4, number=7)
    quaternion = proto.Field(ubii.proto.dataStructure.quaternion_pb_plus.Quaternion, number=8)
    matrix3x2 = proto.Field(ubii.proto.dataStructure.matrix3x2_pb_plus.Matrix3x2, number=9)
    matrix4x4 = proto.Field(ubii.proto.dataStructure.matrix4x4_pb_plus.Matrix4x4, number=10)
    color = proto.Field(ubii.proto.dataStructure.color_pb_plus.Color, number=11)
    touch_event = proto.Field(ubii.proto.dataStructure.touchEvent_pb_plus.TouchEvent, number=12)
    touch_event_list = proto.Field(ubii.proto.dataStructure.touchEvent_pb_plus.TouchEventList, number=13)
    key_event = proto.Field(ubii.proto.dataStructure.keyEvent_pb_plus.KeyEvent, number=14)
    mouse_event = proto.Field(ubii.proto.dataStructure.mouseEvent_pb_plus.MouseEvent, number=15)
    myo_event = proto.Field(ubii.proto.dataStructure.myoEvent_pb_plus.MyoEvent, number=16)
    pose2D = proto.Field(ubii.proto.dataStructure.pose2d_pb_plus.Pose2D, number=17)
    pose3D = proto.Field(ubii.proto.dataStructure.pose3d_pb_plus.Pose3D, number=18)
    object2D = proto.Field(ubii.proto.dataStructure.object2d_pb_plus.Object2D, number=19)
    object3D = proto.Field(ubii.proto.dataStructure.object3d_pb_plus.Object3D, number=20)
    object2D_list = proto.Field(ubii.proto.dataStructure.object2d_pb_plus.Object2DList, number=21)
    object3D_list = proto.Field(ubii.proto.dataStructure.object3d_pb_plus.Object3DList, number=22)
    int32 = proto.Field(proto.INT32, number=23)
    float = proto.Field(proto.FLOAT, number=24)
    int32_list = proto.Field(ubii.proto.dataStructure.lists_pb_plus.Int32List, number=25)
    float_list = proto.Field(ubii.proto.dataStructure.lists_pb_plus.FloatList, number=26)
    double_list = proto.Field(ubii.proto.dataStructure.lists_pb_plus.DoubleList, number=27)
    string_list = proto.Field(ubii.proto.dataStructure.lists_pb_plus.StringList, number=28)
    bool_list = proto.Field(ubii.proto.dataStructure.lists_pb_plus.BoolList, number=29)
    image2D = proto.Field(ubii.proto.dataStructure.image_pb_plus.Image2D, number=30)
    image2D_list = proto.Field(ubii.proto.dataStructure.image_pb_plus.Image2DList, number=31)
    session = proto.Field(ubii.proto.sessions.session_pb_plus.Session, number=32)
    processing_module_list = proto.Field(ubii.proto.processing.processingModule_pb_plus.ProcessingModuleList, number=33)

class TopicDataRecordList(proto.message.Message):
    elements = proto.RepeatedField(TopicDataRecord, number=0)
